language: node_js
node_js: 'lts/*'
cache: yarn
install:
  - yarn
matrix:
  include:
    - name: 'Backend'
      before_install:
        - cd server
      script:
        - yarn lint
    - name: 'Frontend'
      before_install:
        - cd web
      script:
        - yarn lint
        - yarn test
        - yarn build
