dist: xenial
apt:
  packages:
    - google-cloud-sdk
language: node_js
node_js: 10
cache: yarn
install:
  - yarn
matrix:
  include:
    - name: 'Backend'
      before_install:
        - cd server
      before_script:
        - yarn test:emulator &
      script:
        - yarn lint
        - yarn test
        - yarn compile
    - name: 'Frontend'
      before_install:
        - cd web
      script:
        - yarn lint
        - yarn test
        - yarn build
