runtime: nodejs10
service: default

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  # Replace with API key and authentication domain before deployment
  REACT_APP_API_KEY: '<API_KEY>'
  REACT_APP_AUTH_DOMAIN: '<AUTH_DOMAIN>'
